#!/bin/bash

source /opt/app-root/etc/generate_container_user

# replace var in conf files
for f in ${NGINX_CONFIGURATION_PATH}/*.conf
do
	envsubst '${PROXYPASS_TARGET}' < ${f} > ${f}_temp
	cat ${f}_temp > ${f}
	rm ${f}_temp
done 

set -e

exec nginx -g "daemon off;"
